<?php
declare(strict_types=1);

const GAME_STATE_GAME_SETUP = 1;

const GAME_STATE_PLAYER_PLAY_TOKEN = 10;
const GAME_STATE_PLAYER_SANDPIPER_SELECT_ISOPODS = 11;
const GAME_STATE_PLAYER_ROCK_STEAL_CRAB = 12;
const GAME_STATE_PLAYER_WAVE_FLIP_BEACH = 13;
const GAME_STATE_PLAYER_PLAY_AGAIN = 14;

const GAME_STATE_NEXT_PLAYER = 97;
const GAME_STATE_PRE_END_GAME = 98;
const GAME_STATE_END_GAME = 99;

const TRANSITION_END_TURN = 'ENDTURN';
const TRANSITION_PLAY_AGAIN = 'PLAYAGAIN';
const TRANSITION_PLAY_TOKEN = 'PLAYTOKEN';
const TRANSITION_STEAL_CRAB = 'STEALCRAB';
const TRANSITION_FLIP_BEACH = 'FLIPBEACH';
const TRANSITION_SELECT_ISOPODS = 'SELECTISOPODS';
const TRANSITION_NEXT_PLAYER = 'NEXTPLAYER';
const TRANSITION_END_SCORE = 'ENDSCORE';
const TRANSITION_SCORING_FINISHED = 'SCORINGFINISHED';
const TRANSITION_ZOMBIE_PASS = 'ZOMBIEPASS';

const STAT_NO_SANDPIPER = 'no_sandpiper';
const STAT_NO_BEACH = 'no_beach';
const STAT_NO_SHELL = 'no_shell';
const STAT_NO_WAVE = 'no_wave';
const STAT_NO_ISOPOD = 'no_isopod';
const STAT_NO_CRAB = 'no_crab';
const STAT_NO_ROCK = 'no_rock';
const STAT_NO_SEATOKENS = 'no_seatokens';

const SANDPIPER = 'SANDPIPER';
const BEACH = 'BEACH';
const SHELL = 'SHELL';
const WAVE = 'WAVE';
const ISOPOD = 'ISOPOD';
const CRAB = 'CRAB';
const ROCK = 'ROCK';

const SEA_LOCATION = "SEA";
const BAG_LOCATION = "deck";
const PLAY_LOCATION = "play";
const DISCARD_LOCATION = "discard";

const SANDPIPER_PILE_INIT = 100;

const DECK = [
    65 => [ 1 => BEACH, 2 => SANDPIPER ],
    66 => [ 1 => BEACH, 2 => SANDPIPER ],
    67 => [ 1 => BEACH, 2 => SANDPIPER ],
    1 => [ 1 => BEACH, 2 => ISOPOD ],
    2 => [ 1 => BEACH, 2 => ISOPOD ],
    3 => [ 1 => BEACH, 2 => ISOPOD ],
    17 => [ 1 => BEACH, 2 => CRAB ],
    18 => [ 1 => BEACH, 2 => CRAB ],
    38 => [ 1 => BEACH, 2 => ROCK ],
    39 => [ 1 => BEACH, 2 => ROCK ],
    40 => [ 1 => BEACH, 2 => ROCK ],
    41 => [ 1 => BEACH, 2 => ROCK ],
    42 => [ 1 => BEACH, 2 => SHELL ],
    43 => [ 1 => BEACH, 2 => SHELL ],
    44 => [ 1 => BEACH, 2 => SHELL ],
    45 => [ 1 => BEACH, 2 => SHELL ],
    8 => [ 1 => BEACH, 2 => WAVE ],
    9 => [ 1 => BEACH, 2 => WAVE ],
    10 => [ 1 => BEACH, 2 => WAVE ],
    11 => [ 1 => BEACH, 2 => WAVE ],
    12 => [ 1 => BEACH, 2 => WAVE ],
    13 => [ 1 => BEACH, 2 => WAVE ],

    60 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    61 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    62 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    63 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    64 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    68 => [ 1 => SANDPIPER, 2 => CRAB ],
    69 => [ 1 => SANDPIPER, 2 => CRAB ],
    70 => [ 1 => SANDPIPER, 2 => CRAB ],
    26 => [ 1 => SANDPIPER, 2 => ROCK ],
    27 => [ 1 => SANDPIPER, 2 => ROCK ],
    46 => [ 1 => SANDPIPER, 2 => SHELL ],
    47 => [ 1 => SANDPIPER, 2 => SHELL ],
    48 => [ 1 => SANDPIPER, 2 => SHELL ],
    49 => [ 1 => SANDPIPER, 2 => SHELL ],
    
    14 => [ 1 => ISOPOD, 2 => CRAB ],
    15 => [ 1 => ISOPOD, 2 => CRAB ],
    16 => [ 1 => ISOPOD, 2 => CRAB ],
    31 => [ 1 => ISOPOD, 2 => ROCK ],
    32 => [ 1 => ISOPOD, 2 => ROCK ],
    50 => [ 1 => ISOPOD, 2 => SHELL ],
    51 => [ 1 => ISOPOD, 2 => SHELL ],
    52 => [ 1 => ISOPOD, 2 => SHELL ],
    53 => [ 1 => ISOPOD, 2 => SHELL ],
    4 => [ 1 => ISOPOD, 2 => WAVE ],
    5 => [ 1 => ISOPOD, 2 => WAVE ],
    6 => [ 1 => ISOPOD, 2 => WAVE ],
    7 => [ 1 => ISOPOD, 2 => WAVE ],

    33 => [ 1 => CRAB, 2 => ROCK ],
    34 => [ 1 => CRAB, 2 => ROCK ],
    35 => [ 1 => CRAB, 2 => ROCK ],
    36 => [ 1 => CRAB, 2 => ROCK ],
    37 => [ 1 => CRAB, 2 => ROCK ],
    57 => [ 1 => CRAB, 2 => SHELL ],
    58 => [ 1 => CRAB, 2 => SHELL ],
    59 => [ 1 => CRAB, 2 => SHELL ],
    19 => [ 1 => CRAB, 2 => WAVE ],
    20 => [ 1 => CRAB, 2 => WAVE ],
    21 => [ 1 => CRAB, 2 => WAVE ],
    22 => [ 1 => CRAB, 2 => WAVE ],

    28 => [ 1 => ROCK, 2 => SHELL ],
    29 => [ 1 => ROCK, 2 => SHELL ],
    30 => [ 1 => ROCK, 2 => SHELL ],
    23 => [ 1 => ROCK, 2 => WAVE ],
    24 => [ 1 => ROCK, 2 => WAVE ],
    25 => [ 1 => ROCK, 2 => WAVE ],

    54 => [ 1 => SHELL, 2 => WAVE ],
    55 => [ 1 => SHELL, 2 => WAVE ],
    56 => [ 1 => SHELL, 2 => WAVE ],
];

const TEST_DECK_ROCKS = [
    1 => [ 1 => ROCK, 2 => CRAB ],
    2 => [ 1 => ROCK, 2 => CRAB ],
    3 => [ 1 => ROCK, 2 => CRAB ],
    4 => [ 1 => ROCK, 2 => CRAB ],
    5 => [ 1 => ROCK, 2 => CRAB ],
    6 => [ 1 => ROCK, 2 => CRAB ],
    7 => [ 1 => ROCK, 2 => CRAB ],
    8 => [ 1 => ROCK, 2 => CRAB ],
    9 => [ 1 => ROCK, 2 => CRAB ],
    10 => [ 1 => ROCK, 2 => CRAB ],
    11 => [ 1 => ROCK, 2 => CRAB ],
    12 => [ 1 => ROCK, 2 => CRAB ],
    13 => [ 1 => ROCK, 2 => CRAB ],
    14 => [ 1 => ROCK, 2 => CRAB ],
    15 => [ 1 => ROCK, 2 => CRAB ],
    16 => [ 1 => ROCK, 2 => CRAB ],
    17 => [ 1 => ROCK, 2 => CRAB ],
    18 => [ 1 => ROCK, 2 => CRAB ],
    19 => [ 1 => ROCK, 2 => CRAB ],
    20 => [ 1 => ROCK, 2 => CRAB ],
    21 => [ 1 => ROCK, 2 => CRAB ],
    22 => [ 1 => ROCK, 2 => CRAB ],
    23 => [ 1 => ROCK, 2 => CRAB ],
    24 => [ 1 => ROCK, 2 => CRAB ],
    25 => [ 1 => ROCK, 2 => CRAB ],
    26 => [ 1 => ROCK, 2 => CRAB ],
    27 => [ 1 => ROCK, 2 => CRAB ],
    28 => [ 1 => ROCK, 2 => CRAB ],
    29 => [ 1 => ROCK, 2 => CRAB ],
    30 => [ 1 => ROCK, 2 => CRAB ],
    31 => [ 1 => ROCK, 2 => CRAB ],
    32 => [ 1 => ROCK, 2 => CRAB ],
    33 => [ 1 => ROCK, 2 => CRAB ],
    34 => [ 1 => ROCK, 2 => CRAB ],
    35 => [ 1 => ROCK, 2 => CRAB ],
    36 => [ 1 => ROCK, 2 => CRAB ],
    37 => [ 1 => ROCK, 2 => CRAB ],
    38 => [ 1 => ROCK, 2 => CRAB ],
    39 => [ 1 => ROCK, 2 => CRAB ],
    40 => [ 1 => ROCK, 2 => CRAB ],
    41 => [ 1 => ROCK, 2 => CRAB ],
    42 => [ 1 => ROCK, 2 => CRAB ],
    43 => [ 1 => ROCK, 2 => CRAB ],
    44 => [ 1 => ROCK, 2 => CRAB ],
    45 => [ 1 => ROCK, 2 => CRAB ],
    46 => [ 1 => ROCK, 2 => CRAB ],
    47 => [ 1 => ROCK, 2 => CRAB ],
    48 => [ 1 => ROCK, 2 => CRAB ],
    49 => [ 1 => ROCK, 2 => CRAB ],
    50 => [ 1 => ROCK, 2 => CRAB ],
    51 => [ 1 => ROCK, 2 => CRAB ],
    52 => [ 1 => ROCK, 2 => CRAB ],
    53 => [ 1 => ROCK, 2 => CRAB ],
    54 => [ 1 => ROCK, 2 => CRAB ],
    55 => [ 1 => ROCK, 2 => CRAB ],
    56 => [ 1 => ROCK, 2 => CRAB ],
    57 => [ 1 => ROCK, 2 => CRAB ],
    58 => [ 1 => ROCK, 2 => CRAB ],
    59 => [ 1 => ROCK, 2 => CRAB ],
    60 => [ 1 => ROCK, 2 => CRAB ],
    61 => [ 1 => ROCK, 2 => CRAB ],
    62 => [ 1 => ROCK, 2 => CRAB ],
    63 => [ 1 => ROCK, 2 => CRAB ],
    64 => [ 1 => ROCK, 2 => CRAB ],
    65 => [ 1 => ROCK, 2 => CRAB ],
    66 => [ 1 => ROCK, 2 => CRAB ],
    67 => [ 1 => ROCK, 2 => CRAB ],
    68 => [ 1 => ROCK, 2 => CRAB ],
    69 => [ 1 => ROCK, 2 => CRAB ],
    70 => [ 1 => ROCK, 2 => CRAB ],
];

const TEST_DECK_PIPERS = [
    1 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    2 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    3 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    4 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    5 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    6 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    7 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    8 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    9 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    10 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    11 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    12 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    13 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    14 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    15 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    16 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    17 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    18 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    19 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    20 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    21 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    22 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    23 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    24 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    25 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    26 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    27 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    28 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    29 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    30 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    31 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    32 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    33 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    34 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    35 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    36 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    37 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    38 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    39 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    40 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    41 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    42 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    43 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    44 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    45 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    46 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    47 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    48 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    49 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    50 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    51 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    52 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    53 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    54 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    55 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    56 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    57 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    58 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    59 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    60 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    61 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    62 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    63 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    64 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    65 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    66 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    67 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    68 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    69 => [ 1 => SANDPIPER, 2 => ISOPOD ],
    70 => [ 1 => SANDPIPER, 2 => ISOPOD ],
];

const TEST_DECK_BEACHES = [
    1 => [ 1 => BEACH, 2 => SHELL ],
    2 => [ 1 => BEACH, 2 => SHELL ],
    3 => [ 1 => BEACH, 2 => SHELL ],
    4 => [ 1 => BEACH, 2 => SHELL ],
    5 => [ 1 => BEACH, 2 => SHELL ],
    6 => [ 1 => BEACH, 2 => SHELL ],
    7 => [ 1 => BEACH, 2 => SHELL ],
    8 => [ 1 => BEACH, 2 => SHELL ],
    9 => [ 1 => BEACH, 2 => SHELL ],
    10 => [ 1 => BEACH, 2 => SHELL ],
    11 => [ 1 => BEACH, 2 => SHELL ],
    12 => [ 1 => BEACH, 2 => SHELL ],
    13 => [ 1 => BEACH, 2 => SHELL ],
    14 => [ 1 => BEACH, 2 => SHELL ],
    15 => [ 1 => BEACH, 2 => SHELL ],
    16 => [ 1 => BEACH, 2 => SHELL ],
    17 => [ 1 => BEACH, 2 => SHELL ],
    18 => [ 1 => BEACH, 2 => SHELL ],
    19 => [ 1 => BEACH, 2 => SHELL ],
    20 => [ 1 => BEACH, 2 => SHELL ],
    21 => [ 1 => BEACH, 2 => SHELL ],
    22 => [ 1 => BEACH, 2 => SHELL ],
    23 => [ 1 => BEACH, 2 => SHELL ],
    24 => [ 1 => BEACH, 2 => SHELL ],
    25 => [ 1 => BEACH, 2 => SHELL ],
    26 => [ 1 => BEACH, 2 => SHELL ],
    27 => [ 1 => BEACH, 2 => SHELL ],
    28 => [ 1 => BEACH, 2 => SHELL ],
    29 => [ 1 => BEACH, 2 => SHELL ],
    30 => [ 1 => BEACH, 2 => SHELL ],
    31 => [ 1 => BEACH, 2 => SHELL ],
    32 => [ 1 => BEACH, 2 => SHELL ],
    33 => [ 1 => BEACH, 2 => SHELL ],
    34 => [ 1 => BEACH, 2 => SHELL ],
    35 => [ 1 => BEACH, 2 => SHELL ],
    36 => [ 1 => BEACH, 2 => SHELL ],
    37 => [ 1 => BEACH, 2 => SHELL ],
    38 => [ 1 => BEACH, 2 => SHELL ],
    39 => [ 1 => BEACH, 2 => SHELL ],
    40 => [ 1 => BEACH, 2 => SHELL ],
    41 => [ 1 => BEACH, 2 => SHELL ],
    42 => [ 1 => BEACH, 2 => SHELL ],
    43 => [ 1 => BEACH, 2 => SHELL ],
    44 => [ 1 => BEACH, 2 => SHELL ],
    45 => [ 1 => BEACH, 2 => SHELL ],
    46 => [ 1 => BEACH, 2 => SHELL ],
    47 => [ 1 => BEACH, 2 => SHELL ],
    48 => [ 1 => BEACH, 2 => SHELL ],
    49 => [ 1 => BEACH, 2 => SHELL ],
    50 => [ 1 => BEACH, 2 => SHELL ],
    51 => [ 1 => BEACH, 2 => SHELL ],
    52 => [ 1 => BEACH, 2 => SHELL ],
    53 => [ 1 => BEACH, 2 => SHELL ],
    54 => [ 1 => BEACH, 2 => SHELL ],
    55 => [ 1 => BEACH, 2 => SHELL ],
    56 => [ 1 => BEACH, 2 => SHELL ],
    57 => [ 1 => BEACH, 2 => SHELL ],
    58 => [ 1 => BEACH, 2 => SHELL ],
    59 => [ 1 => BEACH, 2 => SHELL ],
    60 => [ 1 => BEACH, 2 => SHELL ],
    61 => [ 1 => BEACH, 2 => SHELL ],
    62 => [ 1 => BEACH, 2 => SHELL ],
    63 => [ 1 => BEACH, 2 => SHELL ],
    64 => [ 1 => BEACH, 2 => SHELL ],
    65 => [ 1 => BEACH, 2 => SHELL ],
    66 => [ 1 => BEACH, 2 => SHELL ],
    67 => [ 1 => BEACH, 2 => SHELL ],
    68 => [ 1 => BEACH, 2 => SHELL ],
    69 => [ 1 => BEACH, 2 => SHELL ],
    70 => [ 1 => BEACH, 2 => SHELL ],
];

const TEST_DECK_WAVES = [
    1 => [ 1 => WAVE, 2 => BEACH ],
    2 => [ 1 => WAVE, 2 => BEACH ],
    3 => [ 1 => WAVE, 2 => BEACH ],
    4 => [ 1 => WAVE, 2 => BEACH ],
    5 => [ 1 => WAVE, 2 => BEACH ],
    6 => [ 1 => WAVE, 2 => BEACH ],
    7 => [ 1 => WAVE, 2 => BEACH ],
    8 => [ 1 => WAVE, 2 => BEACH ],
    9 => [ 1 => WAVE, 2 => BEACH ],
    10 => [ 1 => WAVE, 2 => BEACH ],
    11 => [ 1 => WAVE, 2 => BEACH ],
    12 => [ 1 => WAVE, 2 => BEACH ],
    13 => [ 1 => WAVE, 2 => BEACH ],
    14 => [ 1 => WAVE, 2 => BEACH ],
    15 => [ 1 => WAVE, 2 => BEACH ],
    16 => [ 1 => WAVE, 2 => BEACH ],
    17 => [ 1 => WAVE, 2 => BEACH ],
    18 => [ 1 => WAVE, 2 => BEACH ],
    19 => [ 1 => WAVE, 2 => BEACH ],
    20 => [ 1 => WAVE, 2 => CRAB ],
    21 => [ 1 => WAVE, 2 => ROCK ],
    22 => [ 1 => WAVE, 2 => SANDPIPER ],
    23 => [ 1 => WAVE, 2 => BEACH ],
    24 => [ 1 => WAVE, 2 => SHELL ],
    25 => [ 1 => WAVE, 2 => WAVE ],
    26 => [ 1 => WAVE, 2 => ISOPOD ],
    27 => [ 1 => WAVE, 2 => CRAB ],
    28 => [ 1 => WAVE, 2 => ROCK ],
    29 => [ 1 => WAVE, 2 => SANDPIPER ],
    30 => [ 1 => WAVE, 2 => BEACH ],
    31 => [ 1 => WAVE, 2 => SHELL ],
    32 => [ 1 => WAVE, 2 => WAVE ],
    33 => [ 1 => WAVE, 2 => ISOPOD ],
    34 => [ 1 => WAVE, 2 => CRAB ],
    35 => [ 1 => WAVE, 2 => ROCK ],
    36 => [ 1 => WAVE, 2 => SANDPIPER ],
    37 => [ 1 => WAVE, 2 => BEACH ],
    38 => [ 1 => WAVE, 2 => SHELL ],
    39 => [ 1 => WAVE, 2 => WAVE ],
    40 => [ 1 => WAVE, 2 => ISOPOD ],
    41 => [ 1 => WAVE, 2 => CRAB ],
    42 => [ 1 => WAVE, 2 => ROCK ],
    43 => [ 1 => WAVE, 2 => SANDPIPER ],
    44 => [ 1 => WAVE, 2 => BEACH ],
    45 => [ 1 => WAVE, 2 => SHELL ],
    46 => [ 1 => WAVE, 2 => WAVE ],
    47 => [ 1 => WAVE, 2 => ISOPOD ],
    48 => [ 1 => WAVE, 2 => CRAB ],
    49 => [ 1 => WAVE, 2 => ROCK ],
    50 => [ 1 => WAVE, 2 => SANDPIPER ],
    51 => [ 1 => WAVE, 2 => BEACH ],
    52 => [ 1 => WAVE, 2 => SHELL ],
    53 => [ 1 => WAVE, 2 => WAVE ],
    54 => [ 1 => WAVE, 2 => ISOPOD ],
    55 => [ 1 => WAVE, 2 => CRAB ],
    56 => [ 1 => WAVE, 2 => ROCK ],
    57 => [ 1 => WAVE, 2 => SANDPIPER ],
    58 => [ 1 => WAVE, 2 => BEACH ],
    59 => [ 1 => WAVE, 2 => SHELL ],
    60 => [ 1 => WAVE, 2 => WAVE ],
    61 => [ 1 => WAVE, 2 => ISOPOD ],
    62 => [ 1 => WAVE, 2 => CRAB ],
    63 => [ 1 => WAVE, 2 => ROCK ],
    64 => [ 1 => WAVE, 2 => SANDPIPER ],
    65 => [ 1 => WAVE, 2 => BEACH ],
    66 => [ 1 => WAVE, 2 => SHELL ],
    67 => [ 1 => WAVE, 2 => WAVE ],
    68 => [ 1 => WAVE, 2 => ISOPOD ],
    69 => [ 1 => WAVE, 2 => CRAB ],
    70 => [ 1 => WAVE, 2 => ROCK ],
];

const TEST_DECK_END_GAME_BONUS = [
    1 => [ 1 => ISOPOD, 2 => CRAB ],
    2 => [ 1 => ISOPOD, 2 => CRAB ],
    3 => [ 1 => ISOPOD, 2 => CRAB ],
    4 => [ 1 => BEACH, 2 => SHELL ],
    5 => [ 1 => BEACH, 2 => SHELL ],
    6 => [ 1 => BEACH, 2 => SHELL ],
    7 => [ 1 => BEACH, 2 => SHELL ],
    8 => [ 1 => BEACH, 2 => SHELL ],
    9 => [ 1 => BEACH, 2 => SHELL ],
    10 => [ 1=> WAVE, 2 => WAVE ],
    11 => [ 1=> WAVE, 2 => WAVE ]
];

?>